### ISSUE TITLE
Are most microfacet-based OSL shaders physically incorrect because of fresnel?

### ISSUE THREAD

**Issue by bhouston** [imageworks/OpenShadingLanguage#567] opened 2015-10-18 02:00 UTC
Been trying my hand at OSL a fair bit the last couple days - it is pretty awesome to be honest, great work!  I'm trying to implement Disney's PBR shader in pure OSL and I hope to contribute it back to this project once done.  I have run into a few problems though.  Here is the first:

I notice this pattern or equivalent in a lot of OSL shaders (for example [this one](https://github.com/imageworks/OpenShadingLanguage/blob/master/testsuite/render-microfacet/glossy_glass.osl)):

```
Ci = (Kr * Cs) * microfacet("default", N, U, xalpha, yalpha, eta, 1);
```

I believe that the microfacet shader itself already has dielectric Fresnel built-in, hence the eta term.  Fresnel should go to 1 when dot( N, I ) = 0.  Basically there should be full reflection at grazing angles.  But the above pattern doesn't allow that because even if microfacet() returns 1.0, it is modulated by the specular color.

Basically this means that at anything approaching grazing angles, if you use a non monochromatic specular color / coefficient, you are getting physically incorrect results.  Almost every shader I see in OSL that has a specular component has what I believe is this "error."

I believe that either eta needs to be a color, which you can compute based on the specular color... something like this for each channel:

```
// from solve( f0 = (( 1-n ) / (1+n))^2, n ), assuming other medium is air.
float f0ToDielectricRefractionIndex( float f0 ) {
    return ( sqrt( f0 ) + 1 ) / ( 1 - sqrt( f0 ) );
}
```

Or you need to incorporate specular color into the microfacet distribution call so that it can be modulated to white at the grazing angles.

Or you need to call the microfacet distribution 3 times, once for each of the eta values representative of the specular color.

Disclaimer: I am somewhat new to PBR so I could be wrong about this.

**Comment by bhouston** [comment] 2015-10-18 02:16
Maybe the issue is that there is no non-monochromatic specular with dielectric fresnel materials in physical reality?  I personally can not think of one off the top of my head.  But then why do so may of these models allow for that situation when it is incorrectly represented by these shaders?

BTW the Disney model uses uses a specular color instead of an eta, and uses Schlick's approximation to Fresnel, which always goes to 1, no matter what the F0 color is:

```
// use Schlick's approximation to calculate Fresnel curve using f0 as specular color
color dielectricFresnelReflectance( color f0, vector light, vector half ) {
	return f0 + ( 1 - f0 ) * pow( 1 - dot( light, half ) ), 5 );
}
```

**Comment by aghiles** [comment] 2015-10-18 16:14
Hello Ben,

The lack of non-monochromatic /and/ complex fresnel term is indeed a big issue:  you can’t do metals as it is.

In our OSL shaders, we patch this by having our own fresnel outside of the closure. Note that this is wrong by design though: fresnel has to be applied to each sample, and not on a closure (which is sampled at some <wi,N,wo> at which point you need to apply the proper fresnel function).

In the near term, we will probably add a “complex_ior” parameter (or similar) to the micro-facet distributions.  

Still, it would be good to have a standard way of achieving this,

—
Aghiles
www.3delight.com

**Comment by bhouston** [comment] 2015-10-18 23:42
Hi Aghiles,

Nice to run into you again and to have my suspicions confirmed.  I'll do the Fresnel outside of the closure as well -- it is simple enough.  I do not know the resulting quality implications of this or speed.

Interestingly, the now classic PBRT book has a Fresnel class that is taken as an input to the Microfacet distribution, and they subclass the Fresnel class to represent both dielectics and conductors and the no-Fresnel case.  The class interface is a single function that takes a cosI and returns a spectrum.  I wonder if something like that is possible as an input to the OSL Microfacet closures?

https://github.com/mmp/pbrt-v3/blob/master/src/core/reflection.h#L245

**Comment by aconty** [comment] 2015-10-19 10:57
Hi

We have our own "conductor" closure which is similar to microfacet but implements this complex ior feature. We haven't made it part of the "standard" because, to be honest, we don't seem to agree whether there should be a standard for things like this. Every render does things differently, so is not clear what the closure/protoypes should look like except for very obvious cases.

Alex

**Comment by lgritz** [comment] 2015-10-19 16:57
Everybody seems to use their personal GitHub logins, sometimes I too need a roster to remember which userids correspond to which places.

In case it's not clear, Alex is at SPI. We have indeed phased out our direct use of microfacet, and in general the "combine separate BSDFs in one material". Two BSDFs that are energy preserving individually can be not so when combined if they are not carefully paired. Now we are phasing in more holistic BSDFs that are harder to get wrong no matter how you dial the parameters. Though when we are "layering" or truly mixing materials, we can still have aggregate BSDFs coming out of the shader, but that's a somewhat different situation.

I'm a part of the faction that wants a standard set of closures to be part of the OSL spec, but it is very difficult -- at SPI we have completely revamped our set of closures several times, and are in the midst of a new overhaul now. Every time we say "did we get finally it right this time?" And every time I'm glad we didn't enshrine the last one in the spec and get a little embarrassed about the mismatch between the spec and what we are doing in practice. (In contrast, the language itself has been incredibly stable, as have been the compatibility of all shaders except the "root" node that creates and assembles the closures.)

It seems to me that all the groups and renderers are for the most part converging on a similar set of ideas about BSDFs (and for that matter, methods for integration / light transport). I don't think there are any real secrets here, so I'd certainly be in favor of everybody just laying cards on the table and saying what BSDFs they are using and exactly what the parameters are, and maybe there is a common core subset that we all think are worth making the written spec conform to. If there was consensus, I would be happy to scrap the set of BSDFs described in the spec (and testrender) in favor of a modern set that we all feel is better. That section is by far the weakest part of the document.

**Comment by bhouston** [comment] 2015-10-19 17:58
From an analysis done in collaboration with @anderslanglands, this is what I generally see for raw BSDFs in VRay PRMan, MDL/IRay, and mostly PBRT.  The below is what I consider to be an idealized version that doesn't present all parameter variants that are equivalent:

```
function LambertianReflection(diffuse) {
  return new OrenNayarReflection( diffuse, 0 )
}
function GGXDistribution( roughness, anisotropyU, anisotropyV ) {
  return new GeneralizedTrowbridgeReitzDistribution( roughness, 2, anisotropyU, anisotropyV );
}

{
  // Diffuse:
  bsdfs.add( new OrenNayarReflection( diffuse, roughnessSigma ) );
}

{
  // Glass:
  var microfacetDistribution = new GeneralizedTrowbridgeReitzDistribution( roughness, gamma, anisotropyU, anisotropyV );
  var fresnel = new FresnelDielectric( 1, ior, abbeNumber );
  bsdfs.add( new MicrofacetReflection( reflectance, microfacetDistribution, fresnel ) )
  bsdfs.add( new MicrofacetTransmission( transmittance, microfacetDistribution, 1, ior ) )
}

{
  // Mirror
  var fresnel = new FresnelNoOp();
  bsdfs.add( new SpecularReflection( reflectance, fresnel ) );
}

{
  // Glossy:
  var microfacetDistribution = new BeckmannDistribution( roughness, anisotropyU, anisotropyV );
  var fresnel = new FresnelDielectric( 1, ior, abbeNumber );
  bsdfs.add( new MicrofacetReflection( reflectanceColor, microfacetDistribution, fresnel ) )
  bsdfs.add( new MicrofacetTransmission( transmittanceColor, microfacetDistribution, 1, ior ) )
}

{
  // Metal
  var microfacetDistribution = new GeneralizedTrowbridgeReitzDistribution( roughness, gamma, anisotropyU, anisotropyV );
  var fresnel = new FresnelConductorNK( 1, ior, kappa );
  bsdfs.add( new MicrofacetReflection( 1, microfacetDistribution, fresnel ) );
}

{
  // Subsurface Uniform (the name TabulatedBSSRDF is taken from PBRT)
  bsdfs.add( new TabulatedBSSRDF_FromUniform( emissionColor, absorptionColor, scatteringColor, phaseFunction ) );
}

{
  // Subsurface Multi-Lobe (similar alSurface, PxrSkin)
  var lobes = [
    new SSSLobe( distance1, weight1, color1 ),
    ...
  ];
  
  bsdfs.add( new TabulatedBSSRDF_FromMultiLobe( lobes ) );
}

{
  // Hair
  bsdfs.add( new KayijaKay( diffuse, specular, roughness ) );
}
```

**Comment by bhouston** [comment] 2015-10-19 18:38
BTW some of the key features of the above definition, mostly as a result of me being inspired by @mmp's PBRT v3, are the following:

- The Reflection and Transmission BSDFs are aware of the reflection/transmission colors, thus they can blend to white at Dielectric Fresnel angles if desired or other neat color-specific things.  This is a major limitation of the current standardized OSL closures I am working with -- and the reason for this Github issue.
- Fresnel is pluggable, thus allows for different parameterizations for different Fresnel effects.  Not sure if you need full customization here, or whether the three I proposed above are sufficient.
- The Distribution for the Microfacet distribution is pluggable, thus allowing different parameterizations for different distributions.

The only thing I am not sure on is whether "abbeNumber" should be part of DielectricFresnel or whether it should always be paired with IOR as part of the Reflection/Transmission BSDFs.

**Comment by fpsunflower** [comment] 2015-10-19 18:49
How do you envision pluggable fresnel and microfacet distributions working in the language?

Currently we have used a string enum for the latter and dedicated closures for the former (though as Alex and Larry have said -- the spec is not in sync with our best practices at SPI).

**Comment by bhouston** [comment] 2015-10-19 19:02
@fpsunflower I do not know how OSL should be modified, I am a novice at OSL (but this is also probably why limitations standout so much as I haven't yet learned to work around them.)

I can point to @mmp's PBRT implementation of the Fresnel class here as sort of a best practice as he implements both Conductor and Dielectric based on it:

https://github.com/mmp/pbrt-v3/blob/master/src/core/reflection.h#L245

It is basically a class that returns a Spectrum/Color given ```dot( N, I )```.

**Comment by bhouston** [comment] 2015-10-19 19:16
I am not sure truly pluggable fresnels are required, there really are only 3 types I have ever seen, thus enums work.  I am not beholden to the design I gave in terms of pluggable Fresnels.  But the Fresnel options should be supported with color parameters within the Microfacet BRDF for physical correctness.  So an enum for Fresnel along with optional parameters to specify their inputs is sufficient.

Same with the Distributions, an enum with optional parameters to specify their inputs is sufficient.  There are only a fixed number of interesting Distributions that I know of, so full programmability here is not needed.

V-Ray is using the optional distribution parameters, and while not elegant, it is functional.

**Comment by fpsunflower** [comment] 2015-10-19 20:21
Those are all very reasonable ways of doing it. I'm sure we could agree on something like what you describe. I'd be happy to put forward what we currently use at SPI which I think covers the cases you are interested in.

Where the design space really explodes is when we start considering layering of these basic closures. That's where I think it might be harder to gain consensus, unless someone really wanted to champion a particular approach.

**Comment by anderslanglands** [comment] 2015-10-19 20:31
Layering should be left to the renderer, IMO. As long as the language
allows you to specify that this BSDF goes over this other one, it's up to
the renderer what that means.

The alternative is to try and codify all the different ways this could be
interpreted, which as you say would be an explosion.

**Comment by fpsunflower** [comment] 2015-10-19 20:41
The language itself currently doesn't offer a way of saying "over". But you could define something like:

`closure color over(closure color top, closure color bot);`

It would then be the renderer's problem of deciding how to parse/evaluate/sample a tree of closures that used this primitive.

We'd be very happy if someone were to give this a go inside `testrender`.

**Comment by bhouston** [comment] 2015-10-20 00:06
In my analysis I found these types of layering functions -- I :
```
// Layered
var layers = [
	new Layer( bsdf1, weight1 ),
	new Layer( bsdf2, weight2 ),
	...
	];
bsdfs.add( new WeightedBlend( layers, blendMode = [ additive, normalized, clamped ] ) );

// Scaled
bsdfs.add( new Scaled( bsdf, color ) );

// FresnelBlend
bsdfs.add( new FresnelBlend( ior, weight, overBSDF, baseBSDF ) );
```

BTW the most interesting thing I've noticed in my studies was the MDL material class, it is basically a template you can plug BSDFs into.  I think it is fairly well though out:

```
struct material_emission {
	edf emission = edf(); // Light emission DF
	color intensity = color(0.0);
	intensity_mode mode = intensity_radiant_exitance;
};

struct material_surface {
	bsdf scattering = bsdf(); // Bidirectional scattering DF
	material_emission emission = material_emission();
};

struct material_volume {
	vdf scattering = vdf();
	color absorption_coefficient = 0.0;
	color scattering_coefficient = 0.0;
};

struct material_geometry {
	float3 displacement = float3(0.0);
	float cutout_opacity = 1.0;
	float3 normal = state::normal();
};


struct material {
	uniform bool thin_walled = false;
	material_surface surface = material_surface();
	material_surface backface = material_surface();
	uniform color ior = color(1.0);
	material_volume volume = material_volume();
	material_geometry geometry = material_geometry();
};
```

**Comment by fpsunflower** [comment] 2015-10-20 20:54
Weighted and Scaled are natively supported by OSL (since you can multiply closures by colors and add them).

You can emulate FresnelBlend if your renderer provides the vector `I` and then you can just weight your closures by a `fresnel` based view dependent term. But of course this will break reciprocity of the resulting BRDF.

There are more "correct" ways of doing the fresnel blend, but they require handling the operation on the renderer side. This points back to either an uber-closure model like we are trying to do at SPI, or a more general closure combination mechanism via modifiers like `over()`.

**Comment by lgritz** [comment] 2018-12-29 20:06
Old discussion that seems to have died off (and maybe answered all the original questions?). Closing.

**Closed by lgritz** 2018-12-29 20:06 UTC
