### ISSUE TITLE
Build issues on macOS Catalina (fatal error: 'wchar.h' file not found)

### ISSUE THREAD

**Issue by pjessesco** [imageworks/OpenShadingLanguage#1055] opened 2019-09-05 04:41 UTC
### Problem

**Expected behavior:**  

**Actual behavior:**  CMake works good without warnings, but i couldn't build it.

<img width="764" alt="스크린샷 2019-09-05 오후 1 34 50" src="https://user-images.githubusercontent.com/11532321/64312338-84dac880-cfe2-11e9-9dbf-fad891e8b46b.png">

I guess this issue is related to [this](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624)

### Versions

* OSL branch/version:  https://github.com/imageworks/OpenShadingLanguage/commit/473e1f6e2df1915b54b7f2588e22cd8708824e54
* OS:  macOS Catalina beta
* C++ compiler: AppleClang 11.0.0
* LLVM version: 5.0.2
* OIIO version: 2.0.9

**Comment by lgritz** [comment] 2019-09-05 05:10
That's actually a problem with your Mac. I've had the same trouble myself after certain xcode updates. You need to follow these directions:

https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave/52530212#52530212

Basically, the solution that worked for me boils down to:

    xcode-select --install
    open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

**Comment by pjessesco** [comment] 2019-09-05 05:15
Apple removed that package in Catalina, see link i posted.

**Comment by lgritz** [comment] 2019-09-05 05:28
Ah, I see.

I can't tell from your short error message exactly what file was being compiled when you encountered the error.

OSL itself does not directly reference wchar.h.

OIIO does, but only in one place, guarded by an #ifdef that I think is not executed. 

So you may be getting it through some other dependency that includes it, and thus there may be nothing I can do for you directly. You may still need to follow those directions I quoted above to install the missing headers (as also explained in your link) until we can find out which other library it is that is actually referencing the missing include file.

Can you paste for us the full error log?

**Comment by pjessesco** [comment] 2019-09-05 08:38
<img width="812" alt="스크린샷 2019-09-05 오후 5 34 32" src="https://user-images.githubusercontent.com/11532321/64325594-6cc77100-d003-11e9-9bec-eabd430986e6.png">

I think it is easier to see screenshot, here is [gist](https://gist.github.com/pjessesco/ea4311916be04156c9700681500adc94)

**Comment by lgritz** [comment] 2019-09-05 17:27
I wonder if upgrading LLVM (5!) that you're getting through homebrew would help you here? Current LLVM is 8, release candidates ready for 9.

**Comment by pjessesco** [comment] 2019-09-06 04:49
Thanks, but project(appleseed) requires OSL built with LLVM 5... i'll try it again after Catalina release officially.

**Comment by halirutan** [comment] 2020-02-03 18:38
Are there any news regarding this issue?

Using either the compiler that comes with Xcode or clang 9 installed with Mac Ports results in the same error as above. I used LLVM 9 from Mac Ports and ran make with the following settings:

```
/opt/local/bin/clang++-mp-9.0 --version                                                                                                            
clang version 9.0.1 
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-9.0/bin
```

and I built it with the following command:

```
make LLVM_VERSION=9.0 LLVM_DIRECTORY=/opt/local/libexec/llvm-9.0 \
  MYCXX=/opt/local/bin/clang++-mp-9.0 MYCC=/opt/local/bin/clang-mp-9.0 VERBOSE=1
```

The exact call that errors is

```
/opt/local/libexec/llvm-9.0/bin/clang++ -DOSL_FAST_MATH=1 -D__STDC_LIMIT_MACROS \
-D__STDC_CONSTANT_MACROS -DUSE_STD_REGEX -DOSL_LLVM_VERSION=90 \
-DOSL_LLVM_FULL_VERSION="9.0.1" -std=c++11 \
-I/Users/pscheibe/workspace/OpenShadingLanguage/src/liboslexec \
-I/Users/pscheibe/workspace/OpenShadingLanguage/src/include \
-I/Users/pscheibe/workspace/OpenShadingLanguage/build/macosx/include \
-I/opt/local/include -I/opt/local/include -isystem\ /opt/local/include \
-DOSL_COMPILING_TO_BITCODE=1 -Wno-deprecated-register -O3 -fno-math-errno \
-S -emit-llvm -o 

/Users/pscheibe/workspace/OpenShadingLanguage/build/macosx/src/liboslexec/llvm_ops.s llvm_ops.cpp
In file included from llvm_ops.cpp:101:
In file included from /opt/local/libexec/llvm-9.0/bin/../include/c++/v1/iostream:37:
In file included from /opt/local/libexec/llvm-9.0/bin/../include/c++/v1/ios:214:
In file included from /opt/local/libexec/llvm-9.0/bin/../include/c++/v1/iosfwd:95:
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/wchar.h:118:15: fatal error: 'wchar.h' file not found
#include_next <wchar.h>
```

Any ideas? I'm on macOS Catalina 10.15.3.

**Comment by lgritz** [comment] 2020-02-03 18:48
Yeah, I have run into that wchar.h problem, too, always after an OS or XCode upgrade.
Please look at the top of this thread, I already posted the link to the StackOverflow answer that got me unstuck in the past. (Admittedly, I'm not on Catalina.) Read all the answers and their comments, not just the top one -- several are more recent and may be better fixes.

**Comment by lgritz** [comment] 2020-02-03 18:49
Several of the answers/comments mention setting CPATH in particular ways. That's what I would try first, since it doesn't involve any installs or removals.

**Comment by pjessesco** [comment] 2020-02-04 03:50
Hi, I solved a similar problem with downgrading XCode to 10, but i have no idea how to solve on recent version.

**Comment by halirutan** [comment] 2020-02-04 10:37
@lgritz I had looked into the SO post you mentioned and tried various things. It's just not clear to me what happens, but here is a more elaborate report: I looked up the tool-chain with 

```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

That indicates to me that headers and libraries should come from the Xcode toolchains available. So I checked for `wchar.h`

```
% find . -name "wchar.h"
./Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/wchar.h
./Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/wchar.h
./Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/wchar.h
./Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wchar.h
./Platforms/MacOSX.platform/Developer/SDKs/DriverKit19.0.sdk/System/DriverKit/usr/include/wchar.h
./Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/wchar.h
./Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/wchar.h
./Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/wchar.h
./Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/wchar.h
```

The viable options seem to be the `XcodeDefault.xctoolchain` and the `MacOSX.platform/Developer/SDKs/MacOSX.sdk` but I don't have any in-depth knowledge of how they are different. Using the latter option and setting

```
$ export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
$ make nuke &&  make LLVM_VERSION=9.0 LLVM_DIRECTORY=/opt/local/libexec/llvm-9.0 VERBOSE=1
```

gives a whole lot of other errors.

<details>
  <summary>Log File</summary>
  
  ```
[  2%] Generating llvm_ops.bc.cpp
cd /Users/pscheibe/workspace/OpenShadingLanguage/src/liboslexec && /opt/local/libexec/llvm-9.0/bin/clang++ -DOSL_FAST_MATH=1 -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -DUSE_STD_REGEX -DOSL_LLVM_VERSION=90 -DOSL_LLVM_FULL_VERSION="9.0.1" -std=c++11 -I/Users/pscheibe/workspace/OpenShadingLanguage/src/liboslexec -I/Users/pscheibe/workspace/OpenShadingLanguage/src/include -I/Users/pscheibe/workspace/OpenShadingLanguage/build/macosx/include -I/opt/local/include -I/opt/local/include -isystem\ /opt/local/include -DOSL_COMPILING_TO_BITCODE=1 -Wno-deprecated-register -O3 -fno-math-errno -S -emit-llvm -o /Users/pscheibe/workspace/OpenShadingLanguage/build/macosx/src/liboslexec/llvm_ops.s llvm_ops.cpp
In file included from llvm_ops.cpp:104:
In file included from /Users/pscheibe/workspace/OpenShadingLanguage/src/include/OSL/oslconfig.h:66:
In file included from /opt/local/include/OpenImageIO/errorhandler.h:10:
In file included from /opt/local/include/OpenImageIO/strutil.h:23:
In file included from /opt/local/include/OpenImageIO/hash.h:19:
In file included from /opt/local/libexec/llvm-9.0/bin/../include/c++/v1/unordered_map:409:
In file included from /opt/local/libexec/llvm-9.0/bin/../include/c++/v1/__hash_table:18:
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:314:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:315:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h:749:12: note: 'finite' declared here
extern int finite(double)
           ^
In file included from llvm_ops.cpp:104:
In file included from /Users/pscheibe/workspace/OpenShadingLanguage/src/include/OSL/oslconfig.h:66:
In file included from /opt/local/include/OpenImageIO/errorhandler.h:10:
In file included from /opt/local/include/OpenImageIO/strutil.h:23:
In file included from /opt/local/include/OpenImageIO/hash.h:19:
In file included from /opt/local/libexec/llvm-9.0/bin/../include/c++/v1/unordered_map:409:
In file included from /opt/local/libexec/llvm-9.0/bin/../include/c++/v1/__hash_table:18:
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:316:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:317:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:318:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:319:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?
using ::isgreater;
      ^~
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/functional:731:29: note: '::std::greater' declared here
struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                            ^
In file included from llvm_ops.cpp:104:
In file included from /Users/pscheibe/workspace/OpenShadingLanguage/src/include/OSL/oslconfig.h:66:
In file included from /opt/local/include/OpenImageIO/errorhandler.h:10:
In file included from /opt/local/include/OpenImageIO/strutil.h:23:
In file included from /opt/local/include/OpenImageIO/hash.h:19:
In file included from /opt/local/libexec/llvm-9.0/bin/../include/c++/v1/unordered_map:409:
In file included from /opt/local/libexec/llvm-9.0/bin/../include/c++/v1/__hash_table:18:
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:320:7: error: no member named 'isgreaterequal' in the global namespace; did you mean '::std::greater_equal'?
using ::isgreaterequal;
      ^~
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/functional:760:29: note: '::std::greater_equal' declared here
struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                            ^
In file included from llvm_ops.cpp:104:
In file included from /Users/pscheibe/workspace/OpenShadingLanguage/src/include/OSL/oslconfig.h:66:
In file included from /opt/local/include/OpenImageIO/errorhandler.h:10:
In file included from /opt/local/include/OpenImageIO/strutil.h:23:
In file included from /opt/local/include/OpenImageIO/hash.h:19:
In file included from /opt/local/libexec/llvm-9.0/bin/../include/c++/v1/unordered_map:409:
In file included from /opt/local/libexec/llvm-9.0/bin/../include/c++/v1/__hash_table:18:
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:321:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:322:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:323:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:324:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
In file included from llvm_ops.cpp:104:
In file included from /Users/pscheibe/workspace/OpenShadingLanguage/src/include/OSL/oslconfig.h:66:
In file included from /opt/local/include/OpenImageIO/errorhandler.h:10:
In file included from /opt/local/include/OpenImageIO/strutil.h:23:
In file included from /opt/local/include/OpenImageIO/hash.h:25:
/opt/local/include/OpenImageIO/fmath.h:58:12: error: no member named 'isfinite' in namespace 'std'; did you mean 'finite'?
using std::isfinite;
      ~~~~~^~~~~~~~
           finite
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cmath:315:9: note: 'finite' declared here
using ::isfinite;
        ^
In file included from llvm_ops.cpp:104:
In file included from /Users/pscheibe/workspace/OpenShadingLanguage/src/include/OSL/oslconfig.h:66:
In file included from /opt/local/include/OpenImageIO/errorhandler.h:10:
In file included from /opt/local/include/OpenImageIO/strutil.h:23:
In file included from /opt/local/include/OpenImageIO/hash.h:25:
/opt/local/include/OpenImageIO/fmath.h:59:12: error: no member named 'isinf' in namespace 'std'
using std::isinf;
      ~~~~~^
/opt/local/include/OpenImageIO/fmath.h:60:12: error: no member named 'isnan' in namespace 'std'
using std::isnan;
      ~~~~~^
In file included from llvm_ops.cpp:104:
In file included from /Users/pscheibe/workspace/OpenShadingLanguage/src/include/OSL/oslconfig.h:66:
In file included from /opt/local/include/OpenImageIO/errorhandler.h:10:
In file included from /opt/local/include/OpenImageIO/strutil.h:46:
In file included from /opt/local/include/OpenImageIO/fmt/ostream.h:12:
/opt/local/include/OpenImageIO/fmt/format.h:1729:14: error: expected unqualified-id
    if (std::signbit(value)) {  // value < 0 is false for NaN so use signbit.
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h:170:5: note: expanded from macro 'signbit'
    ( sizeof(x) == sizeof(float)  ? __inline_signbitf((float)(x))        \
    ^
In file included from llvm_ops.cpp:104:
In file included from /Users/pscheibe/workspace/OpenShadingLanguage/src/include/OSL/oslconfig.h:66:
In file included from /opt/local/include/OpenImageIO/errorhandler.h:10:
In file included from /opt/local/include/OpenImageIO/strutil.h:46:
In file included from /opt/local/include/OpenImageIO/fmt/ostream.h:12:
/opt/local/include/OpenImageIO/fmt/format.h:1736:15: error: expected unqualified-id
    if (!std::isfinite(value)) {
              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h:155:5: note: expanded from macro 'isfinite'
    ( sizeof(x) == sizeof(float)  ? __inline_isfinitef((float)(x))       \
    ^
In file included from llvm_ops.cpp:104:
In file included from /Users/pscheibe/workspace/OpenShadingLanguage/src/include/OSL/oslconfig.h:66:
In file included from /opt/local/include/OpenImageIO/errorhandler.h:10:
In file included from /opt/local/include/OpenImageIO/strutil.h:46:
In file included from /opt/local/include/OpenImageIO/fmt/ostream.h:12:
/opt/local/include/OpenImageIO/fmt/format.h:1737:23: error: expected unqualified-id
      auto str = std::isinf(value) ? (fspecs.upper ? "INF" : "inf")
                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h:160:5: note: expanded from macro 'isinf'
    ( sizeof(x) == sizeof(float)  ? __inline_isinff((float)(x))          \
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
  ```
</details>

Using other settings gives other errors. I realize that this is not a problem of OSL because it's LLVM being incompatible with compiler settings. But information is scarce and every supposed-to-be-solution that's on the web just feels like people are fumbling around until they get it working. I couldn't find a reasonable explanation of what really happens, but if someone has further ideas, I'm happy to try them out.

**Comment by halirutan** [comment] 2020-02-04 13:55
# Solution for macOS Catalina 10.15.3

Use Mac Ports for installing LLVM version 9.0 (`sudo port install llvm-9.0`). We're going to use the `clang` and `clang++` compiler that's included in this package for compiling OSL. Therefore, the command to build OSL from inside its directory will be (we nuke any existing build first):

```
make nuke &&  make LLVM_VERSION=9.0 LLVM_DIRECTORY=/opt/local/libexec/llvm-9.0 \
MYCC=/opt/local/libexec/llvm-9.0/bin/clang MYCXX=/opt/local/libexec/llvm-9.0/bin/clang++  -j16
```

Take a good look at your llvm-9.0 directory if you installed it differently and adjust the paths. Also, I specified `-j16` to use 16 parallel threads for building. If you don't have a strong machine, change this or leave it out entirely.

**Attention:** If you only use this, then it will end in the error message as described in the issue. The problem is that `wchar.h` that comes with llvm is only a stub that contains the line

```
#include_next <wchar.h>
```

That means that it expects the real `wchar.h` to be accessible which it is not. The correct `wchar.h` is provided by the command line tools that you need to install. Since this is also a prerequisite to use Mac Ports, you probably already have done this. If not, check the first part of the [installation instructions for Mac Ports](https://www.macports.org/install.php) which explains the two simple steps.

If you have the command line tools, then the folder `/Library/Developer/CommandLineTools` should exist on your machine. In this directory, the different SDKs are available and we'll use this include path **in addition** to the include path that LLVM already uses. Therefore, we set the [following environment](https://clang.llvm.org/docs/CommandGuide/clang.html#environment) variable for `clang++` before building OSL

````
export CPLUS_INCLUDE_PATH=/opt/local/libexec/llvm-9.0/include/c++/v1:/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
```

It is vitally important that you also include LLVM's normal include path because it should first look there! After that, OSL should build fine.

**Comment by lgritz** [comment] 2020-02-04 22:30
Great!  Shall I close the issue?

I renamed this issue title to include a mention of wchar.h, so that next time somebody comes across this problem, it will be easy to search for this issue and point them to the solution.

**Comment by halirutan** [comment] 2020-02-05 00:01
@lgritz Yes, I guess we have enough information why it didn't work and we can keep our fingers crossed that it works for everyone.

If the issue comes up again, you could include a link to this solution into [INSTALL.md](https://github.com/imageworks/OpenShadingLanguage/blob/master/INSTALL.md).

**Closed** 2020-02-05 02:04 UTC

**Comment by lgritz** [comment] 2020-11-25 19:52
Updating: I ran into this problem on a machine with Catalina, and as said earlier in this thread, the original trick of  running macOS_SDK_headers_for_macOS_10.14.pkg that I mentioned above no longer works because 10.15 doesn't include this pkg.

The diagnosis of the problem and the advice from @halirutan is correct but assumes paths for Macports, so just for the record, for anybody using Homebrew, the simple solution is just to set:

```
CPLUS_INCLUDE_PATH=/usr/local/opt/llvm/include/c++/v1:/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
```
